### ISSUE TITLE
go build problem on linux

### ISSUE THREAD

**Issue by mammad145** [bepass-org/warp-plus#100]
after go build this message appear and i cant install it on linux server

root@newhost:~/warp-plus# go build
go: downloading github.com/klauspost/compress v1.16.7
../go/pkg/mod/github.com/refraction-networking/utls@v1.3.3/u_handshake_client.go:15:2: github.com/klauspost/compress@v1.16.7: reading https://proxy.golang.org/github.com/klauspost/compress/@v/v1.16.7.zip: 403 Forbidden

**Comment by markpash** [comment]
Hi, the problem you are having is that you are attempting to install on a server which is likely inside Iran. Iran IP addresses are sanctioned (tahrim), so `go build` doesn't work.

But you can download pre-compiled binaries for your server here: https://github.com/bepass-org/warp-plus/releases
