### ISSUE TITLE
Ability to work with Warp config with other Warp domains

### ISSUE THREAD

**Issue by Amir2367** [bepass-org/warp-plus#105]
Hello, Today, May 20th, severe disturbances in Iran's Internet have started since this morning, I got help from both oblivion and hiddify programs for testing, and now, the result was oblivion and hiddify on the first mobile phone and shuttle with no suffering. Warp IPs do not connect, all the IP ranges are blocked. pi, we have to enter a domain from Warp domains in order to connect to Daro normally, I am asking you, dear manufacturer, to add the possibility of adding a domain instead of an IP in both the core of Wireguard Go and the oblivion program.‌ ( If possible, add the singbox core to the program, with the possibility of editing the config due to minor changes that cause connection to the warp.
Because I was able to connect to Warp with these minor changes)

https://github.com/bepass-org/warp-plus/assets/83357422/c5bba05c-cd7c-404d-b96b-82395d2b0028

**Comment by markpash** [comment]
The program supports setting a custom endpoint. In the latest version you can add any other wireguard config.
