### ISSUE TITLE
New censorship : it's not connecting anymore 

### ISSUE THREAD

**Issue by Rickyrvxlovet** [bepass-org/warp-plus#106]
**Version Number
1.1.3

**Description of the bug
Unable to connect to psiphon nether warp

**How to reproduce
1. Go to '...'.
2. Click '....
3. Scroll down to '....
4. See Error

**Expected behavior
Connecting?!

**Screenshots**.
If applicable, include screenshots to help explain your problem.

**Desktop (please fill in the following information):**.
 - OPERATING SYSTEM: [e.g. iOS]

**Smartphone (please provide the following information):**.
 - OS: [e.g. iOS8.1].

**Additional context
IR-MCI

**Comment by Ahmad-2213** [comment]
IR-MCI has applied new interruptions on Warp Range as shown below:

![image](https://github.com/bepass-org/warp-plus/assets/106820058/a512cbbf-0add-45d7-a5a9-94eb61462e30)

we may need a new method.

**Comment by markpash** [comment]
@Rickyrvxlovet @Ahmad-2213 can you please try the latest release and report back? Thanks ❤️
https://github.com/bepass-org/warp-plus/releases/tag/v1.2.2
