### ISSUE TITLE
add vpn mode on linux

### ISSUE THREAD

**Issue by rashedheydari2001** [bepass-org/warp-plus#111]
example vpn tunnel with root.sh file 
https://github.com/MatsuriDayo/nekoray/blob/main/res/vpn/vpn-run-root.sh
change the settings of the file and add the file into the linux.tar.gz and when i run root.sh file after entering root password rool.sh file launch the warp with vpn mode
launching warp plus alone launch the proxy mode this option is really cool

**Comment by markpash** [comment]
Experimental tun mode is added for linux, it requires some manual commands to make it work, but soon it will be automated.
