### ISSUE TITLE
Error When Running warp-plus on Windows 11

### ISSUE THREAD

**Issue by AliGh1** [bepass-org/warp-plus#114]
### Issue: Error When Running `warp-plus` on Windows 11

**Description:**
Encountered an error when attempting to run the `warp-plus` application after successfully cloning and building the repository. The error indicates that the system cannot find the specified path for the `wgcf-profile.ini` file.

**Environment:**
- **OS:** Microsoft Windows [Version 10.0.22631.3593]
- **Go Version:** go1.22.3 windows/amd64
- **Application Version:** `warp-plus` rev-7beee3e

**Steps to Reproduce:**
1. Open Command Prompt.
2. Navigate to the desired directory: `cd C:\Users\aliag\Downloads`
3. Clone the repository: `git clone https://github.com/bepass-org/warp-plus.git`
4. Navigate into the project directory: `cd warp-plus`
5. Build the project: `go build`
6. Run the application: `warp-plus`

**Expected Result:**
The application should run without errors.

**Actual Result:**
The application fails with the following error message:
```
time=2024-05-23T12:33:29.472+03:30 level=INFO msg="using warp endpoints" endpoints="[[2606:4700:d0:0:9d85:fa03:a42d:4204]:8854 [2606:4700:d0:0:9d85:fa03:a42d:4204]:8854]"
time=2024-05-23T12:33:29.472+03:30 level=INFO msg="running in normal warp mode"
time=2024-05-23T12:33:29.478+03:30 level=ERROR msg="open C:\\Users\\aliag\\AppData\\Local\\cache/warp-plus/primary/wgcf-profile.ini: The system cannot find the path specified."
```

**Additional Information:**
- The error suggests that the application is looking for a configuration file (`wgcf-profile.ini`) in the directory `C:\\Users\\aliag\\AppData\\Local\\cache/warp-plus/primary/`.
- It appears that either the file does not exist, or the directory structure has not been created.
- This issue has only been observed with the most recent commit.

---

**Comment by markpash** [comment]
Hi, that was a bug that existed only on that commit, you were unlucky at that moment for building it :laughing: .
Try the latest release, it should be working fine, unless your ISP is blocking it.

**Comment by mahdigh782** [comment]
Hi
I have the same problem on Ubuntu, currently I am using the latest release
```bash
$ ./warp-plus --version    
refs/tags/v1.2.0
$ ./warp-plus --cache-dir .
time=2024-05-24T00:39:12.618+04:30 level=INFO msg="using warp endpoints" endpoints="[162.159.193.91:1014 162.159.193.91:1014]"
time=2024-05-24T00:39:12.618+04:30 level=INFO msg="running in normal warp mode"
time=2024-05-24T00:39:12.618+04:30 level=ERROR msg="open primary/wgcf-profile.ini: no such file or directory"
$ ls                       
LICENSE  README.md  warp-plus  warp-plus_linux-amd64.zip
```

**Comment by nimbold** [comment]
I also get this error on Fedora. I tried to create the **wgcf-profile.ini** file but I didn't know the format for its entries.

**Comment by markpash** [comment]
@mahdigh782 @nimbold 

try version 1.2.1

**Comment by nimbold** [comment]
Thanks, the new version works!
Cheers
