### ISSUE TITLE
not working on shatel isp

### ISSUE THREAD

**Issue by Daredevil74** [bepass-org/warp-plus#129]
سلام، وقت بخیر، خسته نباشید؛
در ابتدا دو سوال داشتم، با وجود راهنمای دستورات، هرگز نتونستم روی ویندوز از اونها استفاده کنم، انگار فقط برای محیط ترموکس هستن.

‏1. اسکن آیپی تمیز و اندپوینت روی ویندوز و با دستورات cmd مقدوره؟ اگه آره به چه شکل؟

‏2. نسخه آخر برنامه که منتشر کردین بعد از اجرا ارور اتصال به سرور کلودفلر رو میده توی cmd و حتی پوشه staff تشکیل نمیشه در مسیر فایل برنامه. دستی از نسخه های قبلی پوشه رو انتقال دادم اما فایده‌ای نداشت و اتصال برقرار نشد که نشون از مسدود کردن از داخل یا از سمت کلودفلره. آیا تایید میکنید؟

لطفا در صورت امکان مشکل اتصال پروژه روی شاتل رو حل کنید. گویا مخابرات هم به همین صورته و متصل نمیشه.
برنامه oblivion هم که تنظیمات بیشتری داره افاقه نکرد چون از همین پروژه شما استفاده میکنه و ارجاع میدن به شما.
اگه این پایان کار وارپ روی شاتل و سرویس‌دهنده هاییه که با وارپ به مشکل خوردن و نمیشه کار دیگه‌ای کرد، لطفا اعلام کنید.
ممنون از زحماتی که برای برنامه کشیدین و میکشید.

**Comment by Ahmad-2213** [comment]
https://f001.backblazeb2.com/file/geph4-dl/geph-releases/windows-stable/4.10.1/geph-windows-setup.exe
سلام.
این اپلیکیشن Geph رو نصب کنید و در حالت وی پی ان مود (کل ترافیک از طریق Geph بره) روی یکی از سرور ها ( ترجیحا فرانسه ) روشن کنید.
این وی پی ان احتمالا وصل میشه ، اما سرعتش خوب نیست، پس ما ازش برای وصل شدن به Oblivion استفاده میکنیم.
در Oblivion از منوی تنظیمات شبکه ، پیکربندی رو خاموش کنین و rtt رو برابر با 3 ثانیه قرار بدین.
ببینید که وصل میشه در این حالت؟ مثلا توی تلگرام یه پروکسی Socks5 بسازین و تست کنید.
اگر وصل شد ، Geph رو خاموش کنین که ببینیم وصل میمونه یانه؟
فعلا تنها راهی که شاید کار کنه و به ذهم میرسه همینه. اگر وصل موند میشه یه همچین متودی رو به Oblivion اضافه کرد که Handshake رو هندل کنه.

**Comment by Ahmad-2213** [comment]
سلام
این اپلیکیشن Geph رو نصب کنید و در حالت وی پی ان مود (کل ترافیک از طریق Geph بره) روی یکی از سرور ها ( ترجیحا فرانسه ) روشن کنید
این وی پی ان احتمالا وصل میشه ، اما سرعتش خوب نیست، پس ما ازش برای وصل شدن به Oblivion استفاده میکنیم
در Oblivion از منوی تنظیمات شبکه ، پیکربندی رو خاموش کنین و rtt رو برابر با 3 ثانیه قرار بدین
ببینید که وصل میشه در این حالت؟ مثلا توی تلگرام یه پروکسی Socks5 بسازین و تست کنید
اگر وصل شد ، Geph رو خاموش کنین که ببینیم وصل میمونه یانه؟
فعلا تنها راهی که شاید کار کنه و به ذهم میرسه همینه. اگر وصل موند میشه یه همچین متودی رو به Oblivion اضافه کرد که Handshake رو هندل کنه

**Comment by Ahmad-2213** [comment]
> سلام این اپلیکیشن Geph رو نصب کنید و در حالت وی پی ان مود (کل ترافیک از طریق Geph بره) روی یکی از سرور ها ( ترجیحا فرانسه ) روشن کنید این وی پی ان احتمالا وصل میشه ، اما سرعتش خوب نیست، پس ما ازش برای وصل شدن به Oblivion استفاده میکنیم در Oblivion از منوی تنظیمات شبکه ، پیکربندی رو خاموش کنین و rtt رو برابر با 3 ثانیه قرار بدین ببینید که وصل میشه در این حالت؟ مثلا توی تلگرام یه پروکسی Socks5 بسازین و تست کنید اگر وصل شد ، Geph رو خاموش کنین که ببینیم وصل میمونه یانه؟ فعلا تنها راهی که شاید کار کنه و به ذهم میرسه همینه. اگر وصل موند میشه یه همچین متودی رو به Oblivion اضافه کرد که Handshake رو هندل کنه

https://f001.backblazeb2.com/file/geph4-dl/geph-releases/windows-stable/4.10.1/geph-windows-setup.exe

**Comment by S1ipKn0T** [comment]
با سلام، ممنون از زحماتتون بر روی اینترنت من هم به این مشکل خورده و دیگه وصل نمی شه! وارپ شما روی کار من تاثیر بسیار مثبتی داشت لطفا پیگیری کنید و خبرش رو اطلاع رسانی کنید!

**Comment by markpash** [comment]
@Daredevil74 @S1ipKn0T can you please try the latest release and report back? Thanks :heart: 
https://github.com/bepass-org/warp-plus/releases/tag/v1.2.2

**Comment by euphoria360** [comment]
Can confirm its working on TCI ADSL line. Thanks.

**Comment by markpash** [comment]
> > @Daredevil74 @S1ipKn0T can you please try the latest release and report back? Thanks ❤️ https://github.com/bepass-org/warp-plus/releases/tag/v1.2.2
> 
> بله، مشکل حل شده. خسته نباشید
> فقط این فایل dll جایگزین پوشه‌ای هس که در محل فایل برنامه اجرا میشد؟ چون پوشه‌ای ایجاد نشد
> بعد میشه لایسنس هم بهش داد؟
> مجددا تشکر میکنم ازتون بابت پیگیری، روی شاتل اوکیه در حال حاضر

خیر، این فایل dll باید کنار فایل exe قرار بگیره برای اینکه بتونی در سیستم عامل ویندوز از قابلیت tun این برنامه استفاده کنی.

پوشه stuff جایگزین شده به یه پوشه در localappdata توی پوشه یوزر ویندوز.

لایسنس رو میشه بهش داد با استفاده از فلگ
--key
