### ISSUE TITLE
Container images not available

### ISSUE THREAD

**Issue by debMan** [bepass-org/warp-plus#134]
**Version number**
No matters

**Describe the bug**
The container image is not listed in the packages section. Also, after finding the image version from the actions log output, the image pull command failed with an unauthorized message.

**To Reproduce**
1. Go to [Packages](https://github.com/orgs/bepass-org/packages?repo_name=warp-plus)
2. Then, there is no package
3. Find the latest image version from the actions log output ([example](https://github.com/bepass-org/warp-plus/actions/runs/9272247165/job/25509535288))
```
2024/05/28 15:34:46 Publishing ghcr.io/bepass-org/warp-plus:1.2.2
2024/05/28 15:34:46 Tagging ghcr.io/bepass-org/warp-plus:sha-dc4f281
2024/05/28 15:34:46 Tagging ghcr.io/bepass-org/warp-plus:1.2
2024/05/28 15:34:46 Tagging ghcr.io/bepass-org/warp-plus:1
```
4. Pull it on your local machine
```shell
docker image pull ghcr.io/bepass-org/warp-plus:1.2.2
# result:
# Error response from daemon: Head "https://ghcr.io/v2/bepass-org/warp-plus/manifests/1.2.2": unauthorized

```
**Expected behavior**
Pull the image smoothly

**Screenshots**
<img width="358" alt="image" src="https://github.com/bepass-org/warp-plus/assets/12995147/19100f70-36b0-4ebc-a26a-203b64841187">
<img width="526" alt="image" src="https://github.com/bepass-org/warp-plus/assets/12995147/6b96dc85-3da9-4e29-92a7-837821208f9f">

**Comment by markpash** [comment]
It was an organisation permission setting issue. It's now fixed. :heart:
