### ISSUE TITLE
ساخت اکانت های متعدد در کلودفلر

### ISSUE THREAD

**Issue by iHMahmoodi** [bepass-org/warp-plus#137]
سلام 
در این مورد قبلا اینجا نوشته بودم
https://github.com/bepass-org/oblivion-desktop/issues/107

دوستان @ircfspace گفتن که چون به نسخه نسخه ۱.۲.۲ از Warp-plus آپدیت شده، در این مورد اینجا هم بنویسم که پیگیری بشه
با هر اتصال یک یوزر در بخش اکانت کلود فلر وارپ میسازه
در نتیجه بعد از دوبار اتصال تعداد یوزر ها به 5تا میرسه و دیگه خطای هویت سنجی میده چون وارپ اجازه میده 5تا اکانت به یک حساب وصل باشن
این مشکل در نسخه جدید [v0.10.0-beta](https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.10.0-beta)  که الان منتشر شد نه تنها برگشته بلکه با همون اتصال اول 3تا اکانت میسازه و حتی با ساختن اکانت ها هم وصل نمیشه و ارور میده
انگار دائما میخواد اکانت بسازه ولی دیگه جا نداره

**Comment by papampi** [comment]
با درود
من سعی کردم این مشکل رو با استفاده از --wgconf و --config حل کنم ولی موفق نشدم.
با wgconf ران میشه ولی وصل نمیشه و برای config هم نتونستم کانفیگ درست بسازم مرتب ارور میده و خارج میشه

**Comment by Amir2367** [comment]
> با درود من سعی کردم این مشکل رو با استفاده از --wgconf و --config حل کنم ولی موفق نشدم. با wgconf ران میشه ولی وصل نمیشه و برای config هم نتونستم کانفیگ درست بسازم مرتب ارور میده و خارج میشه

Yes,i have the same problem.

**Comment by markpash** [comment]
> با درود من سعی کردم این مشکل رو با استفاده از --wgconf و --config حل کنم ولی موفق نشدم. با wgconf ران میشه ولی وصل نمیشه و برای config هم نتونستم کانفیگ درست بسازم مرتب ارور میده و خارج میشه

Using wgconf with a warp configuration will likely not work because the `reserved` value is not set in your config file.

**Comment by markpash** [comment]
> Is there anyway to set it?

Yes, in the `[Peer]` section of your config, add a line like this: `Reserved = 1,2,3` replacing the three digits with ones that you need to decode from your warp identity. This is very manual, which is why I automated it all in the normal method.

**Comment by papampi** [comment]
Doesn't 1.2.2 have "Automatic warp reserved field by default"?
So anyway to make it automate on wgconf too?

**Comment by papampi** [comment]
There is also another problem when using wgconf, that's scan not working and it can't find clean ip.

**Comment by Amir2367** [comment]
> There is also another problem when using wgconf, that's scan not working and it can't find clean ip.

Yes, I agree, the scanner can't detect the correct IP most of the time.
@markpash

**Comment by markpash** [comment]
> Doesn't 1.2.2 have "Automatic warp reserved field by default"? So anyway to make it automate on wgconf too?

Use the program without wgconf. wgconf is not supposed to be used to connect to warp.



> There is also another problem when using wgconf, that's scan not working and it can't find clean ip.

The wgconf is not supposed to be used for connecting to warp. If you use the program without the `wgconf` flag, it will connect you to warp.



> > There is also another problem when using wgconf, that's scan not working and it can't find clean ip.
> 
> Yes, I agree, the scanner can't detect the correct IP most of the time. @markpash

There is already an issue for the scanner problem. Please don't repeat unrelated bugs in other issues.

This issue is about identity recreation, please stay on topic.

@iHMahmoodi can you provide some logs please?

**Comment by papampi** [comment]
> Use the program without wgconf. wgconf is not supposed to be used to connect to warp.

I was just trying to find a way to bypass the identity problem.

**Comment by iHMahmoodi** [comment]
> > Doesn't 1.2.2 have "Automatic warp reserved field by default"? So anyway to make it automate on wgconf too?
> 
> Use the program without wgconf. wgconf is not supposed to be used to connect to warp.
> 
> > There is also another problem when using wgconf, that's scan not working and it can't find clean ip.
> 
> The wgconf is not supposed to be used for connecting to warp. If you use the program without the `wgconf` flag, it will connect you to warp.
> 
> > > There is also another problem when using wgconf, that's scan not working and it can't find clean ip.
> > 
> > 
> > Yes, I agree, the scanner can't detect the correct IP most of the time. @markpash
> 
> There is already an issue for the scanner problem. Please don't repeat unrelated bugs in other issues.
> 
> This issue is about identity recreation, please stay on topic.
> 
> @iHMahmoodi can you provide some logs please?


`[2024-05-29 15:31:07.479] [info]  past logs was deleted for new connection.
[2024-05-29 15:31:07.483] [info]  ------------------------MetaData------------------------
[2024-05-29 15:31:07.484] [info]  running on: win32 10.0.22631 x64
[2024-05-29 15:31:07.484] [info]  at od: 0.10.0-beta
[2024-05-29 15:31:07.485] [info]  at wp: v1.2.2
[2024-05-29 15:31:07.485] [info]  ls assets/bin: LICENSE,README.md,vbs,warp-plus.exe,wintun.dll
[2024-05-29 15:31:07.485] [info]  method: gool
[2024-05-29 15:31:07.486] [info]  proxyMode: true
[2024-05-29 15:31:07.486] [info]  endpoint: default
[2024-05-29 15:31:07.486] [info]  license: true
[2024-05-29 15:31:07.486] [info]  exe: ******\Oblivion Desktop.exe
[2024-05-29 15:31:07.488] [info]  userData: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop
[2024-05-29 15:31:07.488] [info]  logs: C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\logs
[2024-05-29 15:31:07.489] [info]  ------------------------MetaData------------------------
[2024-05-29 15:31:07.503] [info]  starting wp process...
[2024-05-29 15:31:07.503] [info]  C:\Users\<USERNAME>\AppData\Roaming\oblivion-desktop\warp-plus.exe --bind 127.0.0.1:8090 --key ********* --gool --scan
[2024-05-29 15:31:07.510] [info]  trying to set system proxy...
[2024-05-29 15:31:07.513] [info]  Routing Rules: Customized
time=2024-05-29T15:31:07.556+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s
time=2024-05-29T15:31:07.557+03:30 level=INFO msg="license recreating identity with new license" subsystem=warp/account

time=2024-05-29T15:31:07.558+03:30 level=INFO msg="creating new identity" subsystem=warp/account

[2024-05-29 15:31:07.790] [info]  system proxy has been set.
time=2024-05-29T15:31:09.583+03:30 level=INFO msg="updating account license key" subsystem=warp/account

time=2024-05-29T15:31:11.149+03:30 level=INFO msg="successfully loaded warp identity" subsystem=warp/account

time=2024-05-29T15:31:18.489+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=162.159.193.187 error="read udp 192.168.1.149:58313->162.159.193.187:3138: i/o timeout"

time=2024-05-29T15:31:19.719+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=188.114.98.43 error="invalid handshake response length 16 bytes"

time=2024-05-29T15:31:24.159+03:30 level=INFO msg="scan results" endpoints="[{AddrPort:188.114.99.25:1010 RTT:180.8693ms CreatedAt:2024-05-29 15:31:22.1974867 +0330 +0330 m=+14.654088001} {AddrPort:188.114.97.39:8854 RTT:329.0669ms CreatedAt:2024-05-29 15:31:23.8315176 +0330 +0330 m=+16.288118901}]"
time=2024-05-29T15:31:24.159+03:30 level=INFO msg="using warp endpoints" endpoints="[188.114.99.25:1010 188.114.97.39:8854]"
time=2024-05-29T15:31:24.159+03:30 level=INFO msg="running in warp-in-warp (gool) mode"

time=2024-05-29T15:31:24.159+03:30 level=INFO msg="license recreating identity with new license" subsystem=warp/account

time=2024-05-29T15:31:24.162+03:30 level=INFO msg="creating new identity" subsystem=warp/account

time=2024-05-29T15:31:25.478+03:30 level=INFO msg="updating account license key" subsystem=warp/account

time=2024-05-29T15:31:26.191+03:30 level=ERROR msg="couldn't load primary warp identity"
time=2024-05-29T15:31:26.192+03:30 level=ERROR msg="API request failed with status: 400 Bad Request"

[2024-05-29 15:31:26.204] [info]  wp process exited.
[2024-05-29 15:31:26.213] [info]  trying to disable system proxy...
[2024-05-29 15:31:26.408] [info]  system proxy has been disabled on your system.
`

**Comment by iHMahmoodi** [comment]
> > > Doesn't 1.2.2 have "Automatic warp reserved field by default"? So anyway to make it automate on wgconf too?
> > 
> > 
> > Use the program without wgconf. wgconf is not supposed to be used to connect to warp.
> > > There is also another problem when using wgconf, that's scan not working and it can't find clean ip.
> > 
> > 
> > The wgconf is not supposed to be used for connecting to warp. If you use the program without the `wgconf` flag, it will connect you to warp.
> > > > There is also another problem when using wgconf, that's scan not working and it can't find clean ip.
> > > 
> > > 
> > > Yes, I agree, the scanner can't detect the correct IP most of the time. @markpash
> > 
> > 
> > There is already an issue for the scanner problem. Please don't repeat unrelated bugs in other issues.
> > This issue is about identity recreation, please stay on topic.
> > @iHMahmoodi can you provide some logs please?
> 
> `[2024-05-29 15:31:07.479] [info] past logs was deleted for new connection. [2024-05-29 15:31:07.483] [info] ------------------------MetaData------------------------ [2024-05-29 15:31:07.484] [info] running on: win32 10.0.22631 x64 [2024-05-29 15:31:07.484] [info] at od: 0.10.0-beta [2024-05-29 15:31:07.485] [info] at wp: v1.2.2 [2024-05-29 15:31:07.485] [info] ls assets/bin: LICENSE,README.md,vbs,warp-plus.exe,wintun.dll [2024-05-29 15:31:07.485] [info] method: gool [2024-05-29 15:31:07.486] [info] proxyMode: true [2024-05-29 15:31:07.486] [info] endpoint: default [2024-05-29 15:31:07.486] [info] license: true [2024-05-29 15:31:07.486] [info] exe: ******\Oblivion Desktop.exe [2024-05-29 15:31:07.488] [info] userData: C:\Users<USERNAME>\AppData\Roaming\oblivion-desktop [2024-05-29 15:31:07.488] [info] logs: C:\Users<USERNAME>\AppData\Roaming\oblivion-desktop\logs [2024-05-29 15:31:07.489] [info] ------------------------MetaData------------------------ [2024-05-29 15:31:07.503] [info] starting wp process... [2024-05-29 15:31:07.503] [info] C:\Users<USERNAME>\AppData\Roaming\oblivion-desktop\warp-plus.exe --bind 127.0.0.1:8090 --key ********* --gool --scan [2024-05-29 15:31:07.510] [info] trying to set system proxy... [2024-05-29 15:31:07.513] [info] Routing Rules: Customized time=2024-05-29T15:31:07.556+03:30 level=INFO msg="scanner mode enabled" max-rtt=1s time=2024-05-29T15:31:07.557+03:30 level=INFO msg="license recreating identity with new license" subsystem=warp/account
> 
> time=2024-05-29T15:31:07.558+03:30 level=INFO msg="creating new identity" subsystem=warp/account
> 
> [2024-05-29 15:31:07.790] [info] system proxy has been set. time=2024-05-29T15:31:09.583+03:30 level=INFO msg="updating account license key" subsystem=warp/account
> 
> time=2024-05-29T15:31:11.149+03:30 level=INFO msg="successfully loaded warp identity" subsystem=warp/account
> 
> time=2024-05-29T15:31:18.489+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=162.159.193.187 error="read udp 192.168.1.149:58313->162.159.193.187:3138: i/o timeout"
> 
> time=2024-05-29T15:31:19.719+03:30 level=ERROR msg="ping error" subsystem=scanner subsystem=scanner/engine addr=188.114.98.43 error="invalid handshake response length 16 bytes"
> 
> time=2024-05-29T15:31:24.159+03:30 level=INFO msg="scan results" endpoints="[{AddrPort:188.114.99.25:1010 RTT:180.8693ms CreatedAt:2024-05-29 15:31:22.1974867 +0330 +0330 m=+14.654088001} {AddrPort:188.114.97.39:8854 RTT:329.0669ms CreatedAt:2024-05-29 15:31:23.8315176 +0330 +0330 m=+16.288118901}]" time=2024-05-29T15:31:24.159+03:30 level=INFO msg="using warp endpoints" endpoints="[188.114.99.25:1010 188.114.97.39:8854]" time=2024-05-29T15:31:24.159+03:30 level=INFO msg="running in warp-in-warp (gool) mode"
> 
> time=2024-05-29T15:31:24.159+03:30 level=INFO msg="license recreating identity with new license" subsystem=warp/account
> 
> time=2024-05-29T15:31:24.162+03:30 level=INFO msg="creating new identity" subsystem=warp/account
> 
> time=2024-05-29T15:31:25.478+03:30 level=INFO msg="updating account license key" subsystem=warp/account
> 
> time=2024-05-29T15:31:26.191+03:30 level=ERROR msg="couldn't load primary warp identity" time=2024-05-29T15:31:26.192+03:30 level=ERROR msg="API request failed with status: 400 Bad Request"
> 
> [2024-05-29 15:31:26.204] [info] wp process exited. [2024-05-29 15:31:26.213] [info] trying to disable system proxy... [2024-05-29 15:31:26.408] [info] system proxy has been disabled on your system. `

![Screenshot_20240529_153004_1111](https://github.com/bepass-org/warp-plus/assets/8407057/1b75f067-b636-405b-9fa9-7e81f36c2d89)
![Screenshot_20240529_153117_1111](https://github.com/bepass-org/warp-plus/assets/8407057/38e5401e-9648-4153-be7f-08f15089cb6e)

**Comment by iHMahmoodi** [comment]
> @iHMahmoodi can you try a version of the warp-plus cli client from here? https://github.com/bepass-org/warp-plus/actions/runs/9301376048?pr=143 It's a test build. If you confirm that it fixes your problem, I can make a new release.

OK, I downloaded this 
https://github.com/bepass-org/warp-plus/actions/runs/9301376048/artifacts/1552018188
and open my CMD/Terminal and call warp-plus.exe
but nothing happened, do you have any command or guide to testing that?
Am I doing something wrong?

**Comment by markpash** [comment]
> > > @iHMahmoodi can you try a version of the warp-plus cli client from here? https://github.com/bepass-org/warp-plus/actions/runs/9301376048?pr=143 It's a test build. If you confirm that it fixes your problem, I can make a new release.
> > 
> > 
> > OK, I downloaded this https://github.com/bepass-org/warp-plus/actions/runs/9301376048/artifacts/1552018188 and open my CMD/Terminal and call warp-plus.exe but nothing happened, do you have any command or guide to testing that? Am I doing something wrong?
> 
> time=2024-05-30T15:39:59.976+03:30 level=INFO msg="using warp endpoints" endpoints="[162.159.195.64:859 162.159.195.64:859]" time=2024-05-30T15:39:59.977+03:30 level=INFO msg="running in normal warp mode" time=2024-05-30T15:39:59.977+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path="C:\Users\Hossein Mahmoodi\AppData\Local\cache/warp-plus/primary" error="CreateFile C:\Users\Hossein Mahmoodi\AppData\Local\cache\warp-plus\primary\wgcf-identity.json: The system cannot find the file specified." time=2024-05-30T15:39:59.979+03:30 level=INFO msg="creating new identity" subsystem=warp/account time=2024-05-30T15:40:01.632+03:30 level=INFO msg="successfully loaded warp identity" subsystem=warp/account time=2024-05-30T15:40:08.593+03:30 level=INFO msg="connection test successful" time=2024-05-30T15:40:08.594+03:30 level=INFO msg="serving proxy" address=127.0.0.1:8086

Great, and now there's no duplicate identity created, yes?

**Comment by iHMahmoodi** [comment]
> > > > @iHMahmoodi can you try a version of the warp-plus cli client from here? https://github.com/bepass-org/warp-plus/actions/runs/9301376048?pr=143 It's a test build. If you confirm that it fixes your problem, I can make a new release.
> > > 
> > > 
> > > OK, I downloaded this https://github.com/bepass-org/warp-plus/actions/runs/9301376048/artifacts/1552018188 and open my CMD/Terminal and call warp-plus.exe but nothing happened, do you have any command or guide to testing that? Am I doing something wrong?
> > 
> > 
> > time=2024-05-30T15:39:59.976+03:30 level=INFO msg="using warp endpoints" endpoints="[162.159.195.64:859 162.159.195.64:859]" time=2024-05-30T15:39:59.977+03:30 level=INFO msg="running in normal warp mode" time=2024-05-30T15:39:59.977+03:30 level=INFO msg="failed to load identity" subsystem=warp/account path="C:\Users\Hossein Mahmoodi\AppData\Local\cache/warp-plus/primary" error="CreateFile C:\Users\Hossein Mahmoodi\AppData\Local\cache\warp-plus\primary\wgcf-identity.json: The system cannot find the file specified." time=2024-05-30T15:39:59.979+03:30 level=INFO msg="creating new identity" subsystem=warp/account time=2024-05-30T15:40:01.632+03:30 level=INFO msg="successfully loaded warp identity" subsystem=warp/account time=2024-05-30T15:40:08.593+03:30 level=INFO msg="connection test successful" time=2024-05-30T15:40:08.594+03:30 level=INFO msg="serving proxy" address=127.0.0.1:8086
> 
> Great, and now there's no duplicate identity created, yes?

I just run that as it is without any additional command.
 what is the command to set my license and then check how its work? or I mean how can i set my license into this cli version?

**Comment by markpash** [comment]
great, I made a new release with the fix. (v1.2.3)

**Comment by ircfspace** [comment]
ضمن تشکر از @markpash ،
با توجه به حل‌شدن مشکل در جدیدترین آپدیت از warp-plus، میتونین نسخه دسکتاپ هم مجدد بررسی کنین

https://github.com/bepass-org/oblivion-desktop/releases/tag/v0.10.8-beta
@iHMahmoodi
