### ISSUE TITLE
خطای احراز هویت و لیک شدن لایسنس

### ISSUE THREAD

**Issue by farajimahdi** [bepass-org/warp-plus#138]
**Version number**
All Versions.

**Describe the bug**
متاسفانه بعد از وارد کردن لایسنس معتبر و حداقل یکبار اتصال، لایسنس از اعتبار ساقط میشه و دیگه قابل استفاده نیست.

**Desktop (please complete the following information):**
 - OS: Desktop for windows

**Comment by papampi** [comment]
Same as #137

**Comment by ircfspace** [comment]
مشکل توی این‌نسخه برطرف شده :
https://github.com/bepass-org/warp-plus/releases/tag/v1.2.3
