### ISSUE TITLE
اجرا کردن بر روی سرور لینوکسی و فرستادن تمام ترافیک به وارپ

### ISSUE THREAD

**Issue by mfaridi1394** [bepass-org/warp-plus#152]
سلام دوستان من می خوام وارپ را بر روی سرور لینوکسی ران کنم و کل ترافیک از وارپ رد بشه تا بتونم بر روی این سرور های پکیج هایی که نمی شه نصب کرد رو نصب کرد 

راه حلی دارید؟

**Comment by markpash** [comment]
https://github.com/bepass-org/warp-plus/issues/78#issuecomment-2079889959

**Comment by mfaridi1394** [comment]
ُThank you,
If I want install some packages by ansible what I must do? something like kubernetes packages and docker images?

**Comment by markpash** [comment]
> ُThank you, If I want install some packages by ansible what I must do? something like kubernetes packages and docker images?

Most programs respect the HTTPS_PROXY.... environment variables. There's also an experimental tun mode that works on linux, but be VERY careful using it on a server as you can very easily break SSH. (you need to set up nftables/iptables and routing rules correctly)

**Comment by mfaridi1394** [comment]
Thank you again,
If we  can do  with warp in simple way that is great. 
please add this future to the warp,  we can send all traffic to warp and warp work like router for us.
