### ISSUE TITLE
IPv6 only VPS, api.cloudflareclient.com is IPv4, not IPv6, network is unreachable

### ISSUE THREAD

**Issue by zstdadi** [bepass-org/warp-plus#173]
have set "2606:4700::6810:50e6 api.cloudflareclient.com" in /etc/hosts, no luck.

# ./warp-plus --bind 127.0.0.1:8086 -v -6
time=2024-06-21T08:06:32.302Z level=INFO msg="using warp endpoints" endpoints="[[2606:4700:d0:0:eda3:2f80:c074:7336]:894 [2606:4700:d0:0:eda3:2f80:c074:7336]:894]"
time=2024-06-21T08:06:32.302Z level=INFO msg="running in normal warp mode"
time=2024-06-21T08:06:32.302Z level=INFO msg="failed to load identity" subsystem=warp/account path=/root/.cache/warp-plus/primary error="stat /root/.cache/warp-plus/primary/wgcf-identity.json: no such file or directory"
time=2024-06-21T08:06:32.304Z level=INFO msg="creating new identity" subsystem=warp/account
time=2024-06-21T08:06:32.304Z level=ERROR msg="couldn't load primary warp identity"
time=2024-06-21T08:06:32.305Z level=ERROR msg="Post \"https://api.cloudflareclient.com/v0a4005/reg\": dial tcp 141.101.113.119:443: connect: network is unreachable"

**Comment by Lanius-collaris** [comment]
https://github.com/bepass-org/warp-plus/blob/772b1e1c4e75ed4e8125ebb3327e00cad79d4362/warp/tls.go#L123
`warp-plus` always "resolves" `api.cloudflareclient.com` to one of IPs in `141.101.113.0/24` subnet.

**Comment by zstdadi** [comment]
Could modify these codes to set an IPv6 IP of api.cloudflareclient.com for IPv6 VPS?

**Comment by Lanius-collaris** [comment]
@zstdadi You can upload a `wgcf-identity.json` to that VPS or rebuild a patched warp-plus. 
```
diff --git a/warp/tls.go b/warp/tls.go
index dea305c..e5d0a3f 100644
--- a/warp/tls.go
+++ b/warp/tls.go
@@ -6,7 +6,7 @@ import (
 	"net"
 	"net/netip"
 
-	"github.com/bepass-org/warp-plus/iputils"
+	//"github.com/bepass-org/warp-plus/iputils"
 
 	tls "github.com/refraction-networking/utls"
 )
@@ -116,15 +116,15 @@ func (d *Dialer) makeTLSHelloPacketWithSNICurve(plainConn net.Conn, config *tls.
 
 // TLSDial dials a TLS connection.
 func (d *Dialer) TLSDial(plainDialer *net.Dialer, network, addr string) (net.Conn, error) {
-	sni, _, err := net.SplitHostPort(addr)
+	sni, port, err := net.SplitHostPort(addr)
 	if err != nil {
 		return nil, err
 	}
-	ip, err := iputils.RandomIPFromPrefix(netip.MustParsePrefix("141.101.113.0/24"))
+	/*ip, err := iputils.RandomIPFromPrefix(netip.MustParsePrefix("141.101.113.0/24"))
 	if err != nil {
 		return nil, err
-	}
-	plainConn, err := plainDialer.Dial(network, ip.String()+":443")
+	}*/
+	plainConn, err := plainDialer.Dial(network, "[2606:4700::6810:50e6]:"+port)
 	if err != nil {
 		return nil, err
 	}

```
`go build cmd/warp-plus/main.go`

**Comment by zstdadi** [comment]
Thank you!
