### ISSUE TITLE
[Bug]: Inbound SOCKS connections are closed if there's no upload

### ISSUE THREAD

**Issue by radiumatic** [bepass-org/warp-plus#176]
**Version number**
The version of the application that has the bug.
```refs/tags/v1.2.2```
**Describe the bug**

The inbound SOCKS server closes connections if no upload packet is received after a short time.

**To Reproduce**
1. SSH to a machine
2. Initiate any activity on the server that takes more than 5 seconds to complete.
3. Wait without entering any input
4. The SSH connection gets closed

**Expected behavior**

SSH running indefinitely and connections not being closed.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by markpash** [comment]
This is a bug that I think I've fixed. Hopefully, the next release will be better for you.
