### ISSUE TITLE
شناسایی شدن تحت عنوان بدافزار (Malware alert in AVG)

### ISSUE THREAD

**Issue by b3hzad1** [bepass-org/warp-plus#184]
با سلام خدمت دوستان عزیز
در آپدیت جدید AVG متاسفانه warp-plus تحت عنوان بدافزار (تروجان) شناسایی میشود. یک اسکرین شات از اون رو قرار میدم تا دوستان بررسی بفرمایند که مشکل از کجاست.

Hello, dear friends
In the new AVG update, unfortunately, the warp-plus is identified as trojan malware. I will post a screenshot of it so that friends can check where the problem is.

![avg](https://github.com/bepass-org/warp-plus/assets/12196334/3489baf7-1bf7-4d33-a990-ce68482d3230)

**Comment by markpash** [comment]
Duplicate of #119
