### ISSUE TITLE
warp to warp plus problem

### ISSUE THREAD

**Issue by CyrusTheV** [bepass-org/warp-plus#26]
this error occurs when I tried option 4 :

Please enter your selection [0-5]:4
Downloading and running Warp+ script...
--2024-03-06 20:16:09--  https://raw.githubusercontent.com/Ptechgithub/configs/main/wa.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3186 (3.1K) [text/plain]
Saving to: ‘wa.py’

wa.py                                     100%[=====================================================================================>]   3.11K  --.-KB/s    in 0.001s

2024-03-06 20:16:10 (3.00 MB/s) - ‘wa.py’ saved [3186/3186]

  File "wa.py", line 26
    referrer = input(f"[#] ENTER WARP+ ID  [Your id: {default_id}] : ") or default_id
                                                                     ^
SyntaxError: invalid syntax

**Comment by markpash** [comment]
That python script is not part of this project. Please create an issue here: https://github.com/Ptechgithub/configs/
