### ISSUE TITLE
Are these errors normal?

### ISSUE THREAD

**Issue by CyrusTheV** [bepass-org/warp-plus#27]
2024/03/06 21:09:21 connect to 157.240.205.63:443 failed: listen udp 157.240.205.63:443: bind: cannot assign requested address
2024/03/06 21:09:21 connect to 157.240.205.63:443 failed: listen udp 157.240.205.63:443: bind: cannot assign requested address
2024/03/06 21:09:21 connect to 157.240.205.63:443 failed: listen udp 157.240.205.63:443: bind: cannot assign requested address
2024/03/06 21:09:22 connect to 157.240.205.63:443 failed: listen udp 157.240.205.63:443: bind: cannot assign requested address
2024/03/06 21:09:23 connect to 157.240.205.63:443 failed: listen udp 157.240.205.63:443: bind: cannot assign requested address
2024/03/06 21:09:24 connect to 157.240.205.63:443 failed: listen udp 157.240.205.63:443: bind: cannot assign requested address
2024/03/06 21:09:27 connect to 157.240.205.63:443 failed: listen udp 157.240.205.63:443: bind: cannot assign requested address
2024/03/06 21:09:28 connect to 8.8.8.8:443 failed: listen udp 8.8.8.8:443: bind: cannot assign requested address
2024/03/06 21:09:28 connect to 8.8.8.8:443 failed: listen udp 8.8.8.8:443: bind: cannot assign requested address
2024/03/06 21:09:28 connect to 8.8.8.8:443 failed: listen udp 8.8.8.8:443: bind: cannot assign requested address
2024/03/06 21:09:30 connect to 8.8.8.8:443 failed: listen udp 8.8.8.8:443: bind: cannot assign requested address
2024/03/06 21:09:31 connect to 8.8.8.8:443 failed: listen udp 8.8.8.8:443: bind: cannot assign requested address
2024/03/06 21:09:34 connect to 157.240.205.63:443 failed: listen udp 157.240.205.63:443: bind: cannot assign requested address
2024/03/06 21:09:36 read tcp 172.16.0.2:25531: connection reset by peer
2024/03/06 21:09:47 connect to 157.240.205.63:443 failed: listen udp 157.240.205.63:443: bind: cannot assign requested address
2024/03/06 21:09:50 connect to 216.58.206.46:443 failed: listen udp 216.58.206.46:443: bind: cannot assign requested address
2024/03/06 21:09:50 connect to 216.58.206.46:443 failed: listen udp 216.58.206.46:443: bind: cannot assign requested address
2024/03/06 21:09:51 read tcp 172.16.0.2:18123: connection reset by peer
2024/03/06 21:09:51 connect to 216.58.206.46:443 failed: listen udp 216.58.206.46:443: bind: cannot assign requested address
2024/03/06 21:09:52 connect to 216.58.206.46:443 failed: listen udp 216.58.206.46:443: bind: cannot assign requested address
2024/03/06 21:09:54 connect to 216.58.206.46:443 failed: listen udp 216.58.206.46:443: bind: cannot assign requested address
2024/03/06 21:10:01 read tcp 172.16.0.2:62060: connection reset by peer

**Comment by markpash** [comment]
@CyrusTheV Can you try the latest version please?
https://github.com/bepass-org/warp-plus/releases/tag/v1.1.0
