### ISSUE TITLE
نسخه ویندوز

### ISSUE THREAD

**Issue by mehrab-heidary** [bepass-org/warp-plus#28]
سلام 
این روش برای ویندوز آیا قابل پیاده سازی هست چون خیلی وقته وارپ نسخه ویندوز من با نت مخابرات دیگه فعال نمیشه چطور میتونم فعالش کنم وارپ عالی بود ولی انگار فایروالا ایران بایپسش کردن دیگه فعال نمیشه اگه راهی هست ممنون میشم راهنمایی کنید
ممنون

**Comment by markpash** [comment]
Available here: https://github.com/bepass-org/oblivion-desktop
