### ISSUE TITLE
Changing default DNS server by a command line flag

### ISSUE THREAD

**Issue by morealaz** [bepass-org/warp-plus#30]
How can we change Default DNS server from default Google DNS to something else? I mean by a command line flags instead of editing generated profile file.

**Comment by javidshah2** [comment]
**Use the intra App code of the Google-affiliated Jigsaw company for the convenience of people.

https://github.com/Jigsaw-Code/intra**

**Comment by markpash** [comment]
This is added and will be available in the next release.
