### ISSUE TITLE
[SUGGESTION] Tun Mode

### ISSUE THREAD

**Issue by bart3nder** [bepass-org/warp-plus#40]
Hi, Thanks for the great project.
Is it possible to have a Tun mode for warp-plus so we don't have to use alternative solutions to tunnel traffic? or It would be amazing to have the official Wireguard app with your modifications, so it's very easy and convenient, and resource friendly.

**Comment by euphoria360** [comment]
As a workaround, you can use `tun2socks` ([GitHub page](https://github.com/xjasonlyu/tun2socks)) which only requires running afew commands:
```
ip tuntap add mode tun dev tun2
ip addr add 192.168.30.1/32 dev tun2
ip link set dev tun2 up
tun2socks --device tun://tun2 --proxy socks5://127.0.0.1:8086 --loglevel info
```

**Comment by markpash** [comment]
@euphoria360 @bart3nder I have a testing build that creates a tun interface, you can read about it in this issue #66 .
I'm going to close this issue and please continue discussion in #66 . Please test and let me know if it works for you.
