### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Rickyrvxlovet** [bepass-org/warp-plus#48]
Running in Psiphon mode creates a new identity; I have to update the license key each time.

![image](https://github.com/bepass-org/warp-plus/assets/138698343/c538e822-8631-4714-9b9b-e8e411509718)

**Comment by SoroushImanian** [comment]
دقیقا وقتی با -k لاینسس وارپ رو تغییر میدیم با اجرای مجدد warp یا هر روش دیگه، مجدد لاینسس جدید میگیره و در اصل این تغییر انجام نشده و دوباره از ایدنتیفای جدید استفاده میکنه و قبلی رو که ست کردیم پاک میکنه 😐

**Comment by markpash** [comment]
Thanks for the report, I'll try to fix this in the next version. :heart:

**Comment by Amir2367** [comment]
> Thanks for the report, I'll try to fix this in the next version. ❤️



> دقیقا وقتی با -k لاینسس وارپ رو تغییر میدیم با اجرای مجدد warp یا هر روش دیگه، مجدد لاینسس جدید میگیره و در اصل این تغییر انجام نشده و دوباره از ایدنتیفای جدید استفاده میکنه و قبلی رو که ست کردیم پاک میکنه 😐

دقیقا حتی هنگام که ای پی رو میخوای عوص کنی هم مجددا میاد جنریت میکنه و دوباره ای پی عوض میشه

**Comment by markpash** [comment]
Hi @Rickyrvxlovet @SoroushImanian I have a test build if you'd like to try it out? Please download the right version from the set of artifacts on this page: https://github.com/bepass-org/warp-plus/actions/runs/8482017056

Please let me know if this fixes your issues. Please wipe your stuff directory first as this slightly changes how that works.
Play with it as much as you can and if it fixes your problems, I'll merge this code and release a new version.

**Comment by markpash** [comment]
@Rickyrvxlovet The latest release has the complete fix, if you notice a crash just delete the `stuff` folder and try again.
https://github.com/bepass-org/warp-plus/releases/tag/v1.1.1

With regards to logging, there's a `-v` verbose flag, if you don't give the flag, the logs are reduced. Compared to previous releases the logging is much more clear and useful for finding issues. If you see logs that you think are not needed, please make an issue for it and describe which logs you don't like.
