### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by Xtice** [bepass-org/warp-plus#49]
سلام موقع اجرا این ارور رو میده
دسترسی هم داره ترموکس

time=2024-03-23T17:11:09.901Z level=INFO msg="using warp endpoints" endpoints="[162.159.192.62:7103 162.159.192.62:7103]"
time=2024-03-23T17:11:09.902Z level=INFO msg="running in normal warp mode"
time=2024-03-23T17:11:09.906Z level=ERROR msg="Unable to update bind: permission denied" subsystem=wireguard-go
time=2024-03-23T17:11:09.909Z level=ERROR msg="Unable to update bind: permission denied" subsystem=wireguard-go
time=2024-03-23T17:11:09.909Z level=ERROR msg="permission denied"

**Comment by Amir2367** [comment]
> سلام موقع اجرا این ارور رو میده دسترسی هم داره ترموکس
> 
> time=2024-03-23T17:11:09.901Z level=INFO msg="using warp endpoints" endpoints="[162.159.192.62:7103 162.159.192.62:7103]" time=2024-03-23T17:11:09.902Z level=INFO msg="running in normal warp mode" time=2024-03-23T17:11:09.906Z level=ERROR msg="Unable to update bind: permission denied" subsystem=wireguard-go time=2024-03-23T17:11:09.909Z level=ERROR msg="Unable to update bind: permission denied" subsystem=wireguard-go time=2024-03-23T17:11:09.909Z level=ERROR msg="permission denied"

Yes, I have exactly the same problem.

**Comment by Astra060** [comment]
> Unable to update bind: permission denied

ترجیحا انگلیسی بپرس که همه بتونن جواب بدن. به عنوان ادمین یوزر ترمینال باز کن یا با Nekoray امتحان کن.

**Comment by markpash** [comment]
I've not seen anyone else have this problem so I'm closing for now.
