### ISSUE TITLE
Broken Account Config Saving

### ISSUE THREAD

**Issue by Astra060** [bepass-org/warp-plus#51]
In the 1.0 Version, Account Information will not be saved. I have to enter the key as a parameter each time I want to run my warp plus service. Previous Version did not have this behavior. 
After Registering Warp Plus Key, and the Account is created, on next normal runs a free account is auto generated

**Comment by Amir2367** [comment]
> In the 1.0 Version, Account Information will not be saved. I have to enter the key as a parameter each time I want to run my warp plus service. Previous Version did not have this behavior. After Registering Warp Plus Key, and the Account is created, on next normal runs a free account is auto generated

Yes, I have exactly the same problem

**Comment by Amir2367** [comment]
> Hi @Amir2367 @Astra060 I have a test build if you'd like to try it out? Please download the right version from the set of artifacts on this page: https://github.com/bepass-org/warp-plus/actions/runs/8482017056
> 
> Please let me know if this fixes your issues. Please wipe your `stuff` directory first as this slightly changes how that works. Play with it as much as you can and if it fixes your problems, I'll merge this code and release a new version.

How can I test Termux??

**Comment by Amir2367** [comment]
> Hi @Amir2367 @Astra060 I have a test build if you'd like to try it out? Please download the right version from the set of artifacts on this page: https://github.com/bepass-org/warp-plus/actions/runs/8482017056
> 
> Please let me know if this fixes your issues. Please wipe your `stuff` directory first as this slightly changes how that works. Play with it as much as you can and if it fixes your problems, I'll merge this code and release a new version.

Hi Mark, I tested the version you posted earlier


1_ The first movie (when I enter the command warp-plus-4 and when we exit, the IPs are again broken and
and it connects with IP v6, while it should be connected with v4)

2_ The second movie (sometimes it brings IP v6 first, if there is a problem with the shatel and mci with ipv6 and the config doesn't connect)

3- The third movie (by entering the warp-plus -e command, when we want to change the IP and port, the IP does not change and the IPs of the boiler are connected).

https://github.com/bepass-org/warp-plus/assets/83357422/d34663bd-eb14-4ef4-8332-9f23160f7332


https://github.com/bepass-org/warp-plus/assets/83357422/b39ee687-2eb6-41e2-a104-f7dd613741e0


https://github.com/bepass-org/warp-plus/assets/83357422/032c7896-e7f1-4807-8f37-0cccd8cd43b1

**Comment by Astra060** [comment]
> Hi @Amir2367 @Astra060 I have a test build if you'd like to try it out? Please download the right version from the set of artifacts on this page: https://github.com/bepass-org/warp-plus/actions/runs/8482017056
> 
> Please let me know if this fixes your issues. Please wipe your `stuff` directory first as this slightly changes how that works. Play with it as much as you can and if it fixes your problems, I'll merge this code and release a new version.


Hello again. @markpash, yes this build fixed the issue for me. Tnx,

**Comment by Astra060** [comment]
> > Hi @Amir2367 @Astra060 I have a test build if you'd like to try it out? Please download the right version from the set of artifacts on this page: https://github.com/bepass-org/warp-plus/actions/runs/8482017056
> > Please let me know if this fixes your issues. Please wipe your `stuff` directory first as this slightly changes how that works. Play with it as much as you can and if it fixes your problems, I'll merge this code and release a new version.
> 
> Hi Mark, I tested the version you posted above
> 
> 1_ The first movie (when I enter the command warp-plus-4 and when we exit, the IPs are again broken and and it connects with IP v6, while it should be connected with v4)
> 
> 2_ The second movie (sometimes it brings IP v6 first, if there is a problem with the shatel and mci with ipv6 and the config doesn't connect)
> 
> 3- The third movie (by entering the warp-plus -e command, when we want to change the IP and port, the IP does not change and the IPs of the boiler are connected).
> 4_5778648449729695796.mp4
> [×<MEDIA>@https://private-user-images.githubusercontent.com](https://private-user-images.githubusercontent.com/83357422/318102841-d34663bd-eb14-4ef4-8332-9f23160f7332.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3Nzk4MTAsIm5iZiI6MTcxMTc3OTUxMCwicGF0aCI6Ii84MzM1NzQyMi8zMTgxMDI4NDEtZDM0NjYzYmQtZWIxNC00ZWY0LTgzMzItOWYyMzE2MGY3MzMyLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDA2MTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMjRiMDY0OTJjOTViY2I1NDA3MTdmNGMwNTNhMDNkMDMxMWU3MzA3YmY2MGFkY2E0ODY5MmUyN2JhMDM2YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GTuxdyoPJfp6h5tqNn_QS3BCuDndIyExwPqnhUqRq7E)
> 4_5778648449729695798.mp4
> [×<MEDIA>@https://private-user-images.githubusercontent.com](https://private-user-images.githubusercontent.com/83357422/318103005-b39ee687-2eb6-41e2-a104-f7dd613741e0.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3Nzk4MTAsIm5iZiI6MTcxMTc3OTUxMCwicGF0aCI6Ii84MzM1NzQyMi8zMTgxMDMwMDUtYjM5ZWU2ODctMmViNi00MWUyLWExMDQtZjdkZDYxMzc0MWUwLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDA2MTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmOTU2N2U5YzQ0YjRiNjU2NWQ5ZmZmMTNmNjQ5NzhkZmU0NTI1NjFhNDM0YTVmNDIzMDY0ZDNjZjRhOWE1NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YMjAfU8hBOQBBI5P-LclKq6YzUJSs5cMij6ahA2Jhqo)
> 4_5778648449729695799.mp4
> [×<MEDIA>@https://private-user-images.githubusercontent.com](https://private-user-images.githubusercontent.com/83357422/318103051-032c7896-e7f1-4807-8f37-0cccd8cd43b1.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3Nzk4MTAsIm5iZiI6MTcxMTc3OTUxMCwicGF0aCI6Ii84MzM1NzQyMi8zMTgxMDMwNTEtMDMyYzc4OTYtZTdmMS00ODA3LThmMzctMGNjY2Q4Y2Q0M2IxLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDA2MTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ZjAyNWJjYThmN2FlNGI3NmJkMjU0NTQ0NzJkMDcyNjRlOWJlMTE1OTc3NjAyNzczMTUzNmFmMTA4MjRiMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-_XDSm69Ms-Az2xzjFLelNGEP5BMNYgd7_f33jDiUjQ)

I think it's best to open a separate issue for this

**Comment by markpash** [comment]
@Astra060 The latest release has the complete fix. If you notice a crash just delete the `stuff` folder and try again.
https://github.com/bepass-org/warp-plus/releases/tag/v1.1.1

**Comment by Astra060** [comment]
> @Astra060 The latest release has the complete fix. If you notice a crash just delete the `stuff` folder and try again. https://github.com/bepass-org/warp-plus/releases/tag/v1.1.1

Thanks for the quick implementation!
