### ISSUE TITLE
failed to send handshake initiation,network is unreachable

### ISSUE THREAD

**Issue by Amir2367** [bepass-org/warp-plus#52]
Version:1.1.0

When we run the code, we see the following errors in the picture and the connection is not made and the IP and licenseKey are automatically Changed.

1.Code execution
2.A series of errors
IP and licenseKey are automatically Changed.

 

Android 12
Xiaomi

![Screenshot_2024-03-29-11-09-58-942_com termux](https://github.com/bepass-org/warp-plus/assets/83357422/8d1e7e77-5fd7-4aad-ace7-b05923606bc0)

**Comment by markpash** [comment]
@Amir2367 Try adding the `--scan` parameter as well and report back if you still have issues.

**Comment by Amir2367** [comment]
> @Amir2367 Try adding the `--scan` parameter as well and report back if you still have issues.

Yes, the problem was fixed, but for the time you are in Termux, when you exit and enter again
By typing the command warp-plus or
 warp-plus --gool
 It comes back and gives IP version 6

**Comment by Amir2367** [comment]
> @Amir2367 Try adding the `--scan` parameter as well and report back if you still have issues.

Yes, the problem was fixed, but for the time you are in Termux, when you exit and enter again
By typing the command warp-plus or
warp-plus --gool
It comes back and gives IP version 6

**Comment by markpash** [comment]
> > @Amir2367 Try adding the `--scan` parameter as well and report back if you still have issues.
> 
> Yes, the problem was fixed, but for the time you are in Termux, when you exit and enter again By typing the command warp-plus or warp-plus --gool It comes back and gives IP version 6

The IP does not save anywhere, it's a random IP each time. I recommend you use `warp-plus --scan --gool`
