### ISSUE TITLE
Some basic problems

### ISSUE THREAD

**Issue by Amir2367** [bepass-org/warp-plus#54]
Hi Mark, I tested the version you posted in Actions (warp: refactor identity creation)

1_ The first movie (when I enter the command warp-plus-4 and when we exit, the IPs are again broken and
and it connects with IP v6, while it should be connected with v4)

2_ The second movie (sometimes it brings IP v6 first, if there is a problem with the shatel and mci with ipv6 and the config doesn't connect)

3- The third movie (by entering the warp-plus -e command, when we want to change the IP and port, the IP does not change and the IPs of the boiler are connected).

https://github.com/bepass-org/warp-plus/assets/83357422/1b098495-0d6d-4a8e-855f-a8b5ac318d48

https://github.com/bepass-org/warp-plus/assets/83357422/cdf51788-5ab9-4c9a-9b2d-f1c03831d0d9

https://github.com/bepass-org/warp-plus/assets/83357422/7a39c97c-77ca-4e48-8c10-5c55a0e55313

**Comment by markpash** [comment]
Hi,

Every time you run the command, you need to give the full command. Even after exit, when you run again, you need to give the full command.

The best command I recommend you use is `warp-plus --scan --gool`

**Comment by Amir2367** [comment]
> Hi,
> 
> Every time you run the command, you need to give the full command. Even after exit, when you run again, you need to give the full command.
> 
> The best command I recommend you use is `warp-plus --scan --gool`

Thanks for your Support ❤️
