### ISSUE TITLE
MIPS32 Architecture Release Needed

### ISSUE THREAD

**Issue by imansoleimani** [bepass-org/warp-plus#67]
**Version number**
ALL

**Describe the bug**
One of the most affordable routers in Iran that supports the OPENWRT operating system is the [Xiaomi 4A Gigabit](https://www.digikala.com/product/dkp-1945199) router, which utilizes [MIPS32 architecture](https://openwrt.org/inbox/toh/xiaomi/xiaomi_mi_router_4a_gigabit_edition#info). Unfortunately, the file for this architecture is not available in the downloads section.
Please build and add the MIPS32 architecture file as well.
Thanks

**Screenshots**
Screenshot comparing two files: xray (executable on this router) and Warp-Plus (not executable on this router).
![image](https://github.com/bepass-org/warp-plus/assets/18033133/c4356477-37a1-4ed2-8ad3-b54b38512f12)

**Additional context**
If you need more details, let me know

**Comment by markpash** [comment]
I see, there's also some discussion in #71 
I'll work on this for the next release.

**Comment by markpash** [comment]
The changes required have been merged and will be available in the next release. :heart:
