### ISSUE TITLE
Default directory of the 'stuff' folder

### ISSUE THREAD

**Issue by Hosein-Rahnama** [bepass-org/warp-plus#69]
I usually want to create a link to the executable `warp-plus` and put it in `/usr/bin` folder so that I can run the app from the terminal easily. However, the `stuff` folder pops up in my home directory which is annoying. More surprisingly, if you run the `warp-plus` from other directories in the terminal, then the `stuff` folder appears in those directories too! I think it would be more reasonable for the `stuff` folder to show up in the same original directory where the executable `warp-plus` is.

**Comment by debMan** [comment]
Same issue. It would be nice to have a cli flag to set the `stuff` path.

**Comment by bahmanworld** [comment]
Hi, I really need this flag to set a custom path for the `stuff` folder.
Hopefully this flag will be added to the source code in the next update.

**Comment by markpash** [comment]
I'll improve this for the next release. I will try to make it consistent with other applications and not use a `stuff` folder.

**Comment by bahmanworld** [comment]
Hope this helps till next release:
`forked repo including custom stuff path` 🔽
[https://github.com/bahmanworld/xwarp-plus](https://github.com/bahmanworld/xwarp-plus)

ℹ️ BTW i'm not GO dev

**Comment by debMan** [comment]
Does #80 closes this? @markpash
