### ISSUE TITLE
کرش

### ISSUE THREAD

**Issue by Miserableee** [bepass-org/warp-plus#70]
سلام، هر ورژنی از وارپ رو نصب میکنم برای ویندوز فقط فولدر استاف رو میسازه و میپره بیرون. تمام ورژن هارو هم امتحان کردم، ممنون میشم مشکلش رو درست کنید

**Comment by markpash** [comment]
@Miserableee try using this version for windows: https://github.com/bepass-org/oblivion-desktop/releases
