### ISSUE TITLE
لطفا نسخه 32 بیتی رو هم بروز کنید

### ISSUE THREAD

**Issue by LifeLover-7** [bepass-org/warp-plus#71]
لطفا نسخه 32 بیتی رو هم بروز کنید

**Comment by m0jtabaebrahimi** [comment]
Please support the mips (32bit) architecture for my touter (OpenWRT)

**Comment by Wasoud** [comment]
لطفا نسخه ۳۲ بیتی مربوط به معماری mipsel_24kc رو اضافه کنید.
https://openwrt.org/docs/techref/instructionset/mipsel_24kc
سپاس

**Comment by m0jtabaebrahimi** [comment]
I Use the following parameters to build the executable file for my OpenWRT router:

GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build

My router's CPU architecture is mipsle.

**Comment by khosro0** [comment]
Hello
please support mips 32bit for Router mt7621 cpu type
please

**Comment by khosro0** [comment]
The number of users of the 32-bit mips version is much more than the 64-bit version

**Comment by markpash** [comment]
I will add this for the next release.
