### ISSUE TITLE
enhancement: Provide Dockerfile to run alongside other proxy servers

### ISSUE THREAD

**Issue by debMan** [bepass-org/warp-plus#72]
## Description

As I like to run anything in containers, having a Dockerfile and automated container image builds in order to run this awesome warp-in-warp alongside other proxy providers like `xray` is a big plus from my POV.

## Use case

When you are going to run other projects like [xray-core](https://github.com/XTLS/Xray-core), or [MHSanaei/3x-ui](https://github.com/MHSanaei/3x-ui/) in a container, having this warp-plus as an outbound could help eliminating cost of having foreign servers. With this setup, only a single domestic server would be enough to bypass censorship.  
Also, it's possible to provide domestic domain routing policies if the server is located inside the country with censorship and routing the domestic websites to `freedom` output. 

## Example

Assume that we are going to run this warp-plus as an `outbounds` in an `xray` container. The sample `xray` configuration would be something like this:

```json
{
  // ...
  "inbounds": [
    {
    // ...
    // <YOUR DESIRED INBOUNDS like socks>
    // ...
    }
  ],
  "outbounds": [
    {
            "mux": {
            // ...
            },
            "protocol": "socks",
            "settings": {
                "servers": [
                    {
                        "address": "<warp-plus CONTAINER NAME>",
                        "port": "<warp-plus CONTAINER PORT>",
                        // ...
                    }
                ]
            },
            "streamSettings": {},
            "tag": "proxy"
        },
    {
    // ...
    // < other outbounds like freedom, vmess, vless, etc>
    // ...
    }
  ],
  // ...
}
```

**Comment by debMan** [comment]
going to work on this ASAP.

**Comment by markpash** [comment]
Hi, yeah this is on my to-do list and I'd appreciate any help. Some tips.

There's good solutions to building OCI images of Go tools. This one is something I enjoy using: https://github.com/ko-build/ko

If this doesn't work, then obviously we can just have a standard multi-stage build.
