### ISSUE TITLE
FR : HTTP Proxy Beside Socks5

### ISSUE THREAD

**Issue by amijafi** [bepass-org/warp-plus#73]
please provide http proxy in addition to socks , its very useful for connecting in other apps like twitter and windscribe desktop as upstream proxy

**Comment by markpash** [comment]
Hi, the port runs http and socks5 proxy at the same time. Try it and let me know how it works.

**Comment by amijafi** [comment]
Hi , yes it's there and works well , i tried using it in nekobox as front proxy but i can't use it directly in twitter app
