### ISSUE TITLE
The linux arm64 version does not work properly

### ISSUE THREAD

**Issue by apktopsblog** [bepass-org/warp-plus#81]
I have an xiaomi ax3200 router
I installed the arm64 version, but the connection is not established
If it is connected to the same network with another router with arm7 processor.
Did I download the wrong version or is the problem somewhere else?
These values are displayed by running the warp command.

```
root@OpenWrt:~# warp
time=2024-04-29T21:20:10.596Z level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account
time=2024-04-29T21:20:10.597Z level=INFO msg="successfully generated wireguard configuration" subsystem=warp/account
time=2024-04-29T21:20:10.597Z level=INFO msg="using warp endpoints" endpoints="[162.159.195.127:1180 162.159.195.127:1180]"
time=2024-04-29T21:20:10.597Z level=INFO msg="running in normal warp mode"
time=2024-04-29T21:20:12.785Z level=ERROR msg="listen tcp 127.0.0.1:8086: bind: address already in use"
```

configuration:

```
#!/bin/sh /etc/rc.common

START=91

USE_PROCD=1

PROG=/usr/bin/warp

start_service() {
  args=""
  args="$args -b 127.0.0.1:8086 --scan"
  procd_open_instance
  procd_set_param command $PROG $args
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param respawn
  procd_close_instance
}
```

**Comment by markpash** [comment]
Hi @apktopsblog the logs seem to indicate that the port is already in use. Are you sure there's no other service running on that port? Or perhaps the service is already running? Also if you want to access the proxy from other machines, you need to bind on an address different from `127.0.0.1`. Try using the LAN IP address of this router machine.
