### ISSUE TITLE
help me understand how this program bypass Warp's restriction in Iran

### ISSUE THREAD

**Issue by Amin2460** [bepass-org/warp-plus#82]
what's the difference between this and official warp client on Android? because this works but the official client doesn't. what exactly makes this app work in Iran?

چه تغییری توی برنامه باعث میشه که این توی ایران کار کنه ولی برنامه رسمی کلودفلر کار نکنه ؟

**Comment by markpash** [comment]
Both use wireguard technology. Wireguard is filtered in Iran. This version uses a custom modified wireguard that is not filtered yet.
