### ISSUE TITLE
A question about Warp's ping

### ISSUE THREAD

**Issue by WeebMan1** [bepass-org/warp-plus#86]
I live in middle east(!) and when I use Warp or Warp+ I get germany ping... is there anyway to get ping from UAE or Bahrain? ( I don't mean the IP for a country I just mean ping! after using warp my lowest ping is from Germany but I want the lowest to be for UAE or Bahrain)
Pls help

**Comment by markpash** [comment]
There's no real way to control Warp in Warp location.

**Comment by WeebMan1** [comment]
> There's no real way to control Warp in Warp location.

Thanks for the reply but I mean
When I use warp I get my country IP but I have Germany ping(I mean I have the lowest ping from Germany)... I want to have my country IP (but with UAE or Bahrain ping.... I don't know how to say it but I want to have the lowest ping for gaming!!!!! because some games are blocked in my country!
