### ISSUE TITLE
Connecting and disconnecting

### ISSUE THREAD

**Issue by Daredevil74** [bepass-org/warp-plus#97]
v1.1.3

Connecting and disconnecting after a while

also i need to know how to i can change free license to warp plus in windows?

termux cmd not worked in windows.

**Comment by pizokh** [comment]
> also i need to know how to i can change free license to warp plus in windows?

use --key [license]

**Comment by pizokh** [comment]
on windows you can try this GUI version:
https://github.com/bepass-org/oblivion-desktop
